### ISSUE TITLE
Feature Request: Configureable Values instead of Hardcoding

### ISSUE THREAD

**Issue by djdomi** [whiteshark-1975/CitiesSkyline2-CheatOverhaul#1]
Hei

i would thank you for generating this, but might it be possible to modify the values instead of hard-coding it?

**Comment by whiteshark-1975** [comment]
with config file?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op do 7 dec 2023 om 07:03 schreef DoMeLe ***@***.***>:

**Comment by djdomi** [comment]
yeh for example

**Comment by whiteshark-1975** [comment]
working on a settings file i hope releasing it as 3.16
this week or next week

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op do 7 dec 2023 om 13:07 schreef DoMeLe ***@***.***>:

**Comment by Rene123** [comment]
Love this tool, reminds me of Customize It!

But would be nice when could change those settings with a window in game. Like speedlimiter allows you to set the speed of streets by a little popup window.

**Comment by whiteshark-1975** [comment]
thats in the making but we better wait for the updates since alot will
change

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op di 12 dec 2023 om 07:36 schreef Rene123 ***@***.***>:

**Comment by whiteshark-1975** [comment]
has been handled since 0.3.17

**Comment by djdomi** [comment]
> has been handled since 0.3.17

can you please explain in detail? ;)

**Comment by whiteshark-1975** [comment]
almost all assets have done, i say almost.
All settings are hardcode defaulted to Vanilla setting.
The mod creates a settings file inside your appdata folder that users can edit.
on gamestart the mod verify if the file exist, if it doesnt exist the mod will create a file with vanilla values.
that file is JSON-filetype so very easy to edit.
if on game start the file exist the mod will load all the values from the file and apply them to your game.
in the release package the is a webpage included with a table showing you all affected assets and their original vanila values.
thats it.
every 2 days i upload an update with added assets, this means that every 2 days if you wich to use the new modded assets you need to delete your settingsfile, so that the mod can write a new file.
we are now on version 0.3.18, the version 0.3.19 is already in preview available in the sourcepage. it will be uploaded tommorow with some xtra buildings i couldnt add today like the 2 airports and space center, and the parks.
the final version 0.3.20 will take some days xtra and will contain the extention wings and upgrades for the assets.

**Comment by whiteshark-1975** [comment]
on the request for a live gui, that will only be an option once all assets have been handled and not sure if im going to build this since this might cause weird behaviour in your game. i already had a few try-out live editing values and everytime the game ended up crashing. future patches might resolve this but for now i store the gui in the freezer.
